package idim.lib;

public abstract class Ids {
	public static final int purpleSandID = 201;
	public static final int creepStoneID = 202;
	public static final int purpleGlassID = 510;
	public static final int creepCobbleID = 511;
	public static final int purpleCaveStoneID = 522;
	public static final int purpleCobbleID = 513;
	public static final int purpleCoalOreID = 514;
	public static final int purpleDiamondOreID = 515;
	public static final int purpleDiamondBlockID = 516;
	public static final int purpleGlowstoneID = 517;
	public static final int creepDirtID = 518;
	public static final int purpleSandstoneID = 519;
	public static final int purpleIronOreID = 520;
	public static final int purpleGoldOreID = 521;
	public static final int resistGlassID = 523;
	public static final int purpleEmeraldOreID = 524;
	public static final int lostCactusId = 530;
	public static final int desertCrystalID = 531;
	public static final int lostCrystalID = 532;
	public static final int lostRedstoneOreID = 533;
	public static final int lostDiamondOreID = 534;
	public static final int polishedLostCrystalID = 535;
	public static final int polishedDesertCrystalID = 536;
	public static final int purpleCaveStoneStairsID = 537;
	public static final int purpleCaveCobbleStairsID = 538;
	public static final int creepStoneStairsID = 539;
	public static final int purpleSandStoneStairsID = 540;
	public static final int purpleDiamondOre2 = 541;
	public static final int purpleCaveStoneBricksID = 542;
	public static final int purpleCaveStoneBricksStairsID = 543;
	public static final int zincOreID = 544;
	public static final int zincBlockID = 555;
	public static final int lostZincOreID = 556;
	public static final int lostFishBlockID = 557;
	public static final int palmLogBlockID = 558;
	public static final int palmPlanksBlockID = 559;
	public static final int palmLeavesBlockID = 560;
	public static final int palmWoodSaplingID = 561;
	public static final int glowTorchID = 562;
	
	public static final int purpleDiamondID = 16081;
	public static final int purpleGlowstoneDustID = 16082;
	public static final int lostPearlID = 16083;
	public static final int lostSwordID = 16084;
	public static final int powerRodID = 16085;
	public static final int zincItemID = 16086;
	public static final int coconutItemID = 16087;
}